### ISSUE TITLE
simple error

### ISSUE THREAD

**Issue by johnsanterre** [dssg/eights#36]
exp = e.operate.simple_clf(np.array([[1,1,1],[1,2,3]]), np.array([1,1,2]),RandomForestClassifier())
>>> exp.make_report()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eights/perambulate/perambulate.py", line 162, in make_report
    sub_rep.add_summary_graph_roc_auc()
  File "eights/communicate/communicate.py", line 470, in add_summary_graph_roc_auc
    self.add_summary_graph('roc_auc')
  File "eights/communicate/communicate.py", line 459, in add_summary_graph
    maxy = max(y)
ValueError: max() arg is an empty sequence

**Comment by zar1** [comment]
See my response to iss35

**Comment by johnsanterre** [comment]
See my response to iss35

**Comment by johnsanterre** [comment]
closing this as now merged with 35
